"""
Conversation domain model for BARROW.AI.
Stores chat conversations with full metadata for analytics and auditing.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any, TYPE_CHECKING
from uuid import uuid4

from sqlalchemy import (
    String,
    Text,
    Float,
    Integer,
    Boolean,
    ForeignKey,
    Index,
    CheckConstraint,
    DateTime,
    JSON,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship, synonym
from sqlalchemy.dialects.postgresql import UUID, JSONB

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.domain.session import Session


class Conversation(Base):
    """
    Conversation model representing a single exchange between user and chatbot.
    
    Stores user message, bot response, sources, confidence score, and performance metrics.
    """
    
    __tablename__ = "conversations"
    
    # Primary key
    id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        comment="Unique conversation identifier"
    )
    
    # Foreign key to session
    session_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Session this conversation belongs to"
    )
    
    # Message content (encrypted in production via application layer)
    user_message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Original message from user (encrypted at rest)"
    )
    
    bot_response: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Response generated by the chatbot"
    )
    
    # RAG metadata
    sources: Mapped[Optional[List[Dict[str, Any]]]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Source documents used for RAG (document, section, relevance, chunk_index)"
    )
    
    confidence: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="RAG confidence score (0.0 to 1.0)"
    )
    
    # User feedback
    feedback: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="User feedback: 1 for positive, -1 for negative"
    )
    
    # Channel information
    channel: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Channel: 'web' or 'whatsapp'"
    )
    
    # Performance metrics
    latency_ms: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Total response latency in milliseconds"
    )
    
    cache_hit: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether response came from cache"
    )
    
    # LLM metadata
    llm_model: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="LLM model used for generation"
    )
    
    llm_tokens_used: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Number of tokens used (if available)"
    )
    
    # Processing flags
    fallback_triggered: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether fallback response was used"
    )
    
    validation_failed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether post-generation validation failed"
    )
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False,
        index=True,
        comment="When the conversation was created"
    )
    
    # Relationships
    session: Mapped["Session"] = relationship(
        "Session",
        back_populates="conversations",
        lazy="selectin"
    )
    
    # Aliases for backward compatibility with analytics queries
    response_time = synonym('latency_ms')
    source = synonym('channel')
    
    # Table constraints and indexes
    __table_args__ = (
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_conversations_confidence_range"
        ),
        CheckConstraint(
            "feedback IS NULL OR feedback IN (-1, 1)",
            name="ck_conversations_feedback_valid"
        ),
        CheckConstraint(
            "channel IN ('web', 'whatsapp')",
            name="ck_conversations_channel_valid"
        ),
        Index("idx_conversations_created_at", "created_at"),
        Index("idx_conversations_channel_created", "channel", "created_at"),
        Index("idx_conversations_session_created", "session_id", "created_at"),
        Index("idx_conversations_feedback", "feedback", postgresql_where="feedback IS NOT NULL"),
        Index("idx_conversations_cache_hit", "cache_hit", postgresql_where="cache_hit = true"),
        Index("idx_conversations_recent", "created_at"),
    )
    
    def __repr__(self) -> str:
        return f"<Conversation(id={self.id}, session={self.session_id}, channel={self.channel})>"
    
    def to_dict(self, include_session: bool = False) -> Dict[str, Any]:
        """
        Convert conversation to dictionary.
        
        Args:
            include_session: Whether to include related session data
            
        Returns:
            Dict containing conversation data
        """
        result = {
            "id": str(self.id),
            "session_id": str(self.session_id),
            "user_message": self.user_message,
            "bot_response": self.bot_response,
            "sources": self.sources,
            "confidence": self.confidence,
            "feedback": self.feedback,
            "channel": self.channel,
            "latency_ms": self.latency_ms,
            "cache_hit": self.cache_hit,
            "llm_model": self.llm_model,
            "fallback_triggered": self.fallback_triggered,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
        
        if include_session and self.session:
            result["session"] = self.session.to_dict()
        
        return result


class ConversationSource:
    """
    Pydantic-compatible model for conversation source structure.
    Used for type hints and validation.
    """
    
    document: str
    section: Optional[str] = None
    relevance: float
    chunk_index: Optional[int] = None
    text_preview: Optional[str] = None