import asyncio
import os
import aiofiles
from typing import Optional, Dict

from gradio_client import Client

from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)


class OolelTTSService:
    """
    TTS Service using Oolel Voices (Soynade Research) via Gradio Space.
    Designed for Wolof and Wolof-English/French code-switching.
    """
    
    MAX_CACHE_SIZE = 100
    
    def __init__(self):
        self._cache: Dict[str, bytes] = {}
        self.space_id = settings.OOLEL_TTS_SPACE_ID
        self.api_key = settings.HF_TOKEN.get_secret_value() if settings.HF_TOKEN else None
        self._client = None
            
    async def is_available(self) -> bool:
        """Always return true as we can try to connect to the space."""
        return True

    def _get_client(self) -> Client:
        if self._client is None:
            # We initialize lazily
            self._client = Client(self.space_id, hf_token=self.api_key)
        return self._client

    def _predict_sync(self, text: str) -> str:
        """Run Gradio prediction synchronously."""
        client = self._get_client()
        # The /predict endpoint takes a single text input and returns an audio file path
        result = client.predict(
            text=text,
            api_name="/predict"
        )
        return result

    async def synthesize(
        self,
        text: str,
        language: str = "wolof",
        **kwargs
    ) -> Optional[bytes]:
        """
        Convert text to audio using Oolel Voices Gradio Space.
        
        Args:
            text: Text to speak (supports Wolof/English/French mixing)
            language: Base language (usually wolof)
            
        Returns:
            Raw audio bytes (WAV/FLAC), or None on failure.
        """
        if not text or not text.strip():
            return None

        # Check cache
        cache_key = f"{language}:{text}"
        if cache_key in self._cache:
            return self._cache[cache_key]

        try:
            # First attempt: 30s timeout
            # Second attempt: 15s timeout
            timeouts = [30.0, 15.0]
            audio_path = None
            
            for attempt, timeout in enumerate(timeouts):
                try:
                    logger.info("oolel_tts_gradio_request", text_length=len(text), attempt=attempt+1, timeout=timeout)
                    
                    # Run the synchronous gradio call in a thread with a timeout
                    audio_path = await asyncio.wait_for(
                        asyncio.to_thread(self._predict_sync, text),
                        timeout=timeout
                    )
                    break # Success!
                    
                except asyncio.TimeoutError:
                    logger.warning("oolel_tts_timeout", attempt=attempt+1, timeout_used=timeout)
                except Exception as e:
                    logger.error("oolel_tts_gradio_error", attempt=attempt+1, error=str(e))
                    if attempt == len(timeouts) - 1:
                        raise e
            
            if not audio_path:
                logger.error("oolel_tts_all_attempts_failed")
                return None

            # Read the audio file asynchronously
            async with aiofiles.open(audio_path, mode="rb") as f:
                audio_data = await f.read()
                
            # Clean up the temp file generated by Gradio
            try:
                os.remove(audio_path)
            except Exception as e:
                logger.warning("oolel_tts_cleanup_failed", path=audio_path, error=str(e))

            # Update cache
            if len(self._cache) >= self.MAX_CACHE_SIZE:
                first_key = next(iter(self._cache))
                del self._cache[first_key]
            self._cache[cache_key] = audio_data
            
            logger.info("oolel_tts_success", length=len(audio_data))
            return audio_data

        except asyncio.TimeoutError:
            logger.error("oolel_tts_final_timeout_exceeded")
            return None
        except Exception as e:
            logger.error("oolel_tts_exception", error=str(e))
            return None

# Singleton instance
oolel_tts = OolelTTSService()
