"""
Models package for BARROW.AI.
Contains Pydantic schemas for request/response validation and serialization.
"""

from app.models.request import (
    ChatMessageRequest,
    ChatFeedbackRequest,
    AdminLoginRequest,
    AdminLogin2FARequest,
    AdminRefreshTokenRequest,
    AdminChangePasswordRequest,
    AdminResetPasswordRequest,
    AdminEnable2FARequest,
    AdminVerify2FARequest,
    AdminDisable2FARequest,
    WhatsAppWebhookRequest,
    KnowledgeDocumentUploadRequest,
    BroadcastRequest,
    PaginationParams,
    DateRangeParams,
)

from app.models.response import (
    ChatMessageResponse,
    ChatHistoryResponse,
    ErrorResponse,
    HealthResponse,
    TokenResponse,
    AdminUserResponse,
    AdminSessionResponse,
    AnalyticsOverviewResponse,
    AnalyticsQuestionsResponse,
    AnalyticsSentimentResponse,
    AnalyticsLatencyResponse,
    ConversationListResponse,
    ConversationDetailResponse,
    KnowledgeDocumentResponse,
    KnowledgeDocumentListResponse,
    AuditLogResponse,
    AuditLogListResponse,
    WhatsAppOptOutResponse,
    CacheStatsResponse,
    MetricsResponse,
    PaginatedResponse,
)

__all__ = [
    # Request models
    "ChatMessageRequest",
    "ChatFeedbackRequest",
    "AdminLoginRequest",
    "AdminLogin2FARequest",
    "AdminRefreshTokenRequest",
    "AdminChangePasswordRequest",
    "AdminResetPasswordRequest",
    "AdminEnable2FARequest",
    "AdminVerify2FARequest",
    "AdminDisable2FARequest",
    "WhatsAppWebhookRequest",
    "KnowledgeDocumentUploadRequest",
    "BroadcastRequest",
    "PaginationParams",
    "DateRangeParams",
    
    # Response models
    "ChatMessageResponse",
    "ChatHistoryResponse",
    "ErrorResponse",
    "HealthResponse",
    "TokenResponse",
    "AdminUserResponse",
    "AdminSessionResponse",
    "AnalyticsOverviewResponse",
    "AnalyticsQuestionsResponse",
    "AnalyticsSentimentResponse",
    "AnalyticsLatencyResponse",
    "ConversationListResponse",
    "ConversationDetailResponse",
    "KnowledgeDocumentResponse",
    "KnowledgeDocumentListResponse",
    "AuditLogResponse",
    "AuditLogListResponse",
    "WhatsAppOptOutResponse",
    "CacheStatsResponse",
    "MetricsResponse",
    "PaginatedResponse",
]