"""
Tests unitaires du validateur de sortie.
Vérifie la validation des réponses générées par le LLM.
"""

import pytest
from app.services.validation.output_validator import OutputValidator
from app.core.exceptions import ValidationException


class TestOutputValidator:
    """Tests du validateur de réponses."""
    
    def setup_method(self):
        self.validator = OutputValidator()
    
    def test_valid_response_passes(self):
        """Une réponse valide passe la validation."""
        response = (
            "NETSYSTEME provides comprehensive IT and cybersecurity solutions. "
            "Our experts assist with network infrastructure, cloud and support.\n\n"
            "[Source: Services.docx, Section 2]"
        )
        sources = [{"text": "IT solutions and cloud support", "document": "Services.docx"}]
        
        is_valid, final, meta = self.validator.validate_response(
            response, sources, channel="web", strict_mode=False
        )
        assert is_valid is True
        assert len(final) >= 50
    
    def test_slogan_check_skipped(self):
        """Le slogan n'est plus forcé pour le bot générique."""
        response = "NETSYSTEME provides excellent IT services and customer support across all sectors."
        sources = []
        
        is_valid, final, meta = self.validator.validate_response(
            response, sources, channel="web", strict_mode=False
        )
        assert is_valid is True
        assert "slogan_check_skipped" in meta.get("validations_performed", [])
    
    def test_forbidden_term_rejected(self):
        """Un terme interdit est rejeté."""
        response = "This response is completely stupid and idiotically generated by the system."
        sources = []
        
        with pytest.raises(ValidationException):
            self.validator.validate_response(
                response, sources, channel="web", strict_mode=True
            )
        
        # En mode non-strict, le fallback est utilisé
        is_valid, final, meta = self.validator.validate_response(
            response, sources, channel="web", strict_mode=False
        )
        assert is_valid is False
        assert "forbidden_term_detected" in meta.get("validations_performed", [])
    
    def test_whatsapp_truncation(self):
        """Les messages WhatsApp sont tronqués si trop longs."""
        response = "A" * 5000 + ". End of message."
        sources = []
        
        is_valid, final, meta = self.validator.validate_response(
            response, sources, channel="whatsapp", strict_mode=False
        )
        assert len(final) <= 4000
        assert "truncated_for_whatsapp" in meta.get("fixes_applied", [])
    
    def test_empty_response_invalid(self):
        """Une réponse vide est invalide."""
        sources = []
        
        is_valid, final, meta = self.validator.validate_response(
            "", sources, channel="web", strict_mode=False
        )
        assert not is_valid
        assert "empty_response" in meta.get("validations_performed", [])

